### ISSUE TITLE
Upload Reviews to Kitsu from Houdini

### ISSUE THREAD

**Issue by MustafaJafar** [ynput/ayon-kitsu#51]
Hello, 
I'd like to report to issues: 
1. Support uploading review from Houdini.
  Basically, I was able to achieve that by adding `review` family to these two lines.
  https://github.com/ynput/ayon-kitsu/blob/d59b9dbe78ffcb5989ee99ce6f35d04a9f2d28f9/client/ayon_kitsu/plugins/publish/integrate_kitsu_note.py#L15
  https://github.com/ynput/ayon-kitsu/blob/d59b9dbe78ffcb5989ee99ce6f35d04a9f2d28f9/client/ayon_kitsu/plugins/publish/integrate_kitsu_review.py#L13
2. The previous modification worked for me until, recently I started seeing this strange error. my mp4 file is a valid file and I can open it.
    ```
    DEBUG: Found review at: \\storage\work\ayon_projects\Robo\Assets\Character\bigrobo\publish\review\reviewMain\v014\robo_bigrobo_reviewMain_v014_h264.mp4
    DEBUG: http://192.168.1.4:8800 "POST /api/actions/tasks/fa73d6f0-7a4e-497d-98c0-60415f1a389f/comments/f6294d50-1def-4f13-9dba-337959060e75/add-preview HTTP/1.1" 500 2965
    Traceback (most recent call last):
      File "C:\Users\<my-user-name>\AppData\Local\Ynput\AYON\dependency_packages\ayon_2307191209_windows.zip\dependencies\pyblish\plugin.py", line 527, in __explicit_process
        runner(*args)
      File "E:\Ynput\ayon-kitsu\client\ayon_kitsu\plugins\publish\integrate_kitsu_review.py", line 35, in process
        gazu.task.add_preview(
      File "C:\Users\<my-user-name>\AppData\Local\Ynput\AYON\dependency_packages\ayon_2307191209_windows.zip\dependencies\gazu\task.py", line 919, in add_preview
        preview_file = create_preview(
      File "C:\Users\<my-user-name>\AppData\Local\Ynput\AYON\dependency_packages\ayon_2307191209_windows.zip\dependencies\gazu\task.py", line 870, in create_preview
        return raw.post(path, revision, client=client)
      File "C:\Users\<my-user-name>\AppData\Local\Ynput\AYON\dependency_packages\ayon_2307191209_windows.zip\dependencies\gazu\client.py", line 230, in post
        check_status(response, path)
      File "C:\Users\<my-user-name>\AppData\Local\Ynput\AYON\dependency_packages\ayon_2307191209_windows.zip\dependencies\gazu\client.py", line 326, in check_status
        raise ServerErrorException(path)
    gazu.exception.ServerErrorException: actions/tasks/fa73d6f0-7a4e-497d-98c0-60415f1a389f/comments/f6294d50-1def-4f13-9dba-337959060e75/add-preview
    ```
    Also, when I tried to perform the above query `actions/tasks/fa73d6f0-7a4e-497d-98c0-60415f1a389f/comments/f6294d50-1def-4f13-9dba-337959060e75/add-preview` from my VS code Thunder client. it worked as expected and didn't return 500. but, then the uploaded review on my kitsu doesn't look correct. 
    ![Animation_62](https://github.com/ynput/ayon-kitsu/assets/20871534/620951b3-55b3-429b-82c1-9fd947a61a1f)

**Comment by MustafaJafar** [comment]
I can't reproduce this issue any more. I can't tell when it was fixed.
![Animation_94](https://github.com/user-attachments/assets/54116209-690e-451b-9fd1-5bccf75c0b97)

For information: I no longer need to hack around the code to add kitsu tag to the review family. 
I only need to update the kitsu addon settings.
- `ayon+settings://kitsu/publish/CollectKitsuFamily/profiles`

![image](https://github.com/user-attachments/assets/eb4c6fa5-e76c-492a-b5df-48ba3e8519d5)
