### ISSUE TITLE
Handle gazu.exception.NotAuthenticatedException

### ISSUE THREAD

**Issue by johhnry** [ynput/ayon-kitsu#93]
### Is there an existing issue for this?

- [x] I have searched the existing issues and added correct labels.

## Current Behavior
After some time, the gazu auth token is not valid anymore:

```
2024-12-18 16:37:58 INFO       Kitsu           create_or_update_task: {'task_id': '86f49f26-e831-4376-9397-341bdb09563f', 'project_id': 'ed1a6ba5-701d-41a7-a575-a4e044c54580'}
Exception in thread Thread-310 (_handle_eio_message):
Traceback (most recent call last):
File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.11/threading.py", line 982, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.11/site-packages/socketio/client.py", line 512, in _handle_eio_message
self._handle_event(pkt.namespace, pkt.id, pkt.data)
File "/usr/local/lib/python3.11/site-packages/socketio/client.py", line 386, in _handle_event
r = self._trigger_event(data[0], namespace, *data[1:])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/socketio/client.py", line 434, in _trigger_event
return handler(*args)
^^^^^^^^^^^^^^
File "/service/processor/processor.py", line 209, in <lambda>
lambda data: create_or_update_task(self, data),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/service/processor/update_from_kitsu.py", line 201, in create_or_update_task
entity = gazu.task.get_task(data["task_id"])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/gazu/cache.py", line 204, in wrapper
return function(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/gazu/task.py", line 595, in get_task
return raw.get("data/tasks/%s/full" % task_id["id"], client=client)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/gazu/client.py", line 206, in get
check_status(response, path)
File "/usr/local/lib/python3.11/site-packages/gazu/client.py", line 312, in check_status
raise NotAuthenticatedException(path)
gazu.exception.NotAuthenticatedException: data/tasks/86f49f26-e831-4376-9397-341bdb09563f/full
```

## Expected Behavior
We should have a mechanism to auto re-login when it happens. For now I have to restart the worker.

### Steps To Reproduce:

1. Start the Kitsu service
2. Wait for weeks
3. After some time it's not authenticated anymore

### Version
ayon-kitsu: 1.2.4

### What platform were you running when you found the bug?
Linux - Ubuntu

### Relevant log output:

```shell

```

**Comment by johhnry** [comment]
Duplicate of #66 my bad
